variables:
- group: shared

trigger:
  branches:
    include: 
    - develop
    - master
  paths:
    include: 
     - /src/*

resources:
  repositories:
  - repository: devops
    type: git
    name: pub/devops
    ref: main

stages:
- template: azure-pipelines/Tools1.WmiExplorer/main.yml@devops